name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile # optional, --immutable
      
      - name: Build
        run:  npm run build
        
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_OTUS_63127 }}'
          channelId: live
          projectId: otus-63127

      - name: Git Config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      
      - name: Create Git Release
        run: npm run release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          

